version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install aws-sam-cli
  build:
    commands:
      - sam build
  post_build:
    commands:
      - sam deploy --resolve-s3 --no-confirm-changeset --no-fail-on-empty-changeset --stack-name aws-lambda-cft --capabilities CAPABILITY_IAM --region us-east-1
